# Generated by Django 6.0.6 on 2026-07-05 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_esp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_med', models.CharField(max_length=100)),
                ('desc_med', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pac', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('datanasc', models.DateField()),
                ('numtelefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_uni', models.CharField(max_length=100)),
                ('endereco_uni', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=100)),
                ('crm_prof', models.CharField(max_length=20, unique=True)),
                ('id_esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solic', models.DateField(auto_now_add=True)),
                ('status_solic', models.CharField(max_length=50)),
                ('id_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_itemsolic', models.DecimalField(decimal_places=1, max_digits=20)),
                ('id_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
                ('id_solic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitacaomedicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_con', models.DateField()),
                ('hora_con', models.TimeField()),
                ('status_con', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], max_length=20)),
                ('id_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissionalsaude')),
                ('id_uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesaude')),
            ],
        ),
    ]
