# Generated by Django 6.0.6 on 2026-07-05 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='id_pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profissionalsaude'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_uni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidadesaude'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='id_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medicamento'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='id_solic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.solicitacaomedicamento'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='id_esp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especialidade'),
        ),
        migrations.AlterField(
            model_name='solicitacaomedicamento',
            name='id_pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente'),
        ),
    ]
