# Generated by Django 6.0.6 on 2026-07-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_consulta_id_pac_alter_consulta_id_prof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='id_solic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitacaomedicamento'),
        ),
        migrations.AlterField(
            model_name='solicitacaomedicamento',
            name='status_solic',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
