# Generated by Django 6.0.6 on 2026-07-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_itemsolicitacao_id_solic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
