# Generated by Django 6.0.6 on 2026-07-05 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consulta_observacoes_medicamento_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 números.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numtelefone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 números.', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=24),
        ),
    ]
