# Generated by Django 6.0.6 on 2026-07-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paciente_cpf_alter_paciente_numtelefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status_con',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacaomedicamento',
            name='status_solic',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='endereco_uni',
            field=models.CharField(max_length=150),
        ),
    ]
