# Generated by Django 6.0.6 on 2026-07-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_consulta_status_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status_con',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], default='AGENDADA', max_length=50),
        ),
    ]
